backlightcolor:Disabled
compatfantasyzonefix:off
compatignorevolumechanges:off
compatimmediaterepaints:off
compatmcv3horizfovfix:off
compatoverrideplatchecks:on
compatsiemensfriendlydrawing:off
compattranstooriginonreset:off
dojaversion:200
fontoffset:0
fps:0
fpshack:Default
phone:Standard
rotate:0
scrheight:800
scrwidth:800
sound:off
soundfont:Default
spdhackm3ghalfres:off
spdhackmcv3halfres:off
spdhackmcv3nolighting:off
spdhacknoalpha:off
textfont:Default
